// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6P1f46FDngFxE8M9ZsdaSobL8eqdhVRE',
    appId: '1:308210196026:web:f7aba3d35bf230d7f31f03',
    messagingSenderId: '308210196026',
    projectId: 'tasktrackerapp-4904e',
    authDomain: 'tasktrackerapp-4904e.firebaseapp.com',
    storageBucket: 'tasktrackerapp-4904e.firebasestorage.app',
    measurementId: 'G-X7VJT0PML3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAc24_zed9byFnx3JO2o-YCswi0VvxMsE',
    appId: '1:308210196026:android:74f1b75c65d2d798f31f03',
    messagingSenderId: '308210196026',
    projectId: 'tasktrackerapp-4904e',
    storageBucket: 'tasktrackerapp-4904e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNue9S4D9jlNkkOC2JrI86B6-lGIUiK6M',
    appId: '1:308210196026:ios:b3d71d09b37f76ebf31f03',
    messagingSenderId: '308210196026',
    projectId: 'tasktrackerapp-4904e',
    storageBucket: 'tasktrackerapp-4904e.firebasestorage.app',
    iosBundleId: 'com.example.taskApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNue9S4D9jlNkkOC2JrI86B6-lGIUiK6M',
    appId: '1:308210196026:ios:b3d71d09b37f76ebf31f03',
    messagingSenderId: '308210196026',
    projectId: 'tasktrackerapp-4904e',
    storageBucket: 'tasktrackerapp-4904e.firebasestorage.app',
    iosBundleId: 'com.example.taskApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6P1f46FDngFxE8M9ZsdaSobL8eqdhVRE',
    appId: '1:308210196026:web:046e8dde3cab4c49f31f03',
    messagingSenderId: '308210196026',
    projectId: 'tasktrackerapp-4904e',
    authDomain: 'tasktrackerapp-4904e.firebaseapp.com',
    storageBucket: 'tasktrackerapp-4904e.firebasestorage.app',
    measurementId: 'G-CLYBCQ5WN1',
  );
}
